### PR TITLE
Retrying the request if the keepalive connection failed (fixes #256)

### LINKED ISSUE #256: RTMPTSocket reconnect?
server i am sending my rtmpt requests to (nginx) has a request count limit after limit is exceeded http keep-alive connection is being dropped. lf.swift treats it as connection was closed and stops streaming. 
can you point me to the best place to look into it?
@shogo4405

### PR DESCRIPTION
**Pull request by geeee**

### CODE REVIEW

File: Sources/RTMP/RTMPTSocket.swift [hunk 1]
```diff
@@ -129,9 +132,22 @@ final class RTMPTSocket: NSObject, RTMPSocketCompatible {
...
+                    logger.verbose("Will retry request for path=\(lastRequestPathComponent)")
+                }
+                isRetryingRequest = true
+                doRequest(lastRequestPathComponent, lastRequestData, listen)
+            }
+
             return
         }
 
+        isRetryingRequest = false
```
Comment (zhuker) [inline Sources/RTMP/RTMPTSocket.swift]: Should be synchronized? (Like output queue sync)
